[package]
name = "RustyBear-Engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.23.0"
lazy_static = "1.4.0"
vulkano = "0.32.3"
winit = "0.28.2"
